apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
rules:
- apiGroups: [""]  # for core API group its empty for the named API group need to specify the name
  resources: ["pods"]
  verbs:
  - get
  - list
  - watch
  - create
  - update 
  - delete 
- apiGroups: [""]
  resources: ["ConfigMaP"]
  verbs: ["create", "delete"]
