apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer_granualr
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  resourceNames:
    - "blue"
    - "orange"
