# To limit resources in a namespace create a ResourceQuota object as below
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: bharath

spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 5Gi
    limits.cpu: "10"
    limits.memory: 10Gi