apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: logs-events
  name: logs-events
spec:
  containers:
  - image: kodekloud/event-simulator
    name: logs-events
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
