apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bharathuser-developer-binding
subjects:
- kind: User
  name: bharathuser
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io