apiVersion: v1
kind: ReplicationController
metadata:
  name: bharathapp-replicationset
  labels:
    app: bharathapp
    type: front-end
spec:
  template:
    metadata:
      name: bharaths-pod
      labels:
        app: bharathapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3


