apiVersion: v1
kind: Pod
metadata:
  name: bharathpod
spec:
  containers:
    - name: bharathscontainer
      image: nginx
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"