apiVersion: v1
kind: Pod
metadata:
  labels:
    name: webapp-pod
  name: webapp-pod

spec:
  containers:
    - image: kodekloud/simple-webapp-mysql
      name: webapp
      envFrom:
        - secretRef:
            name: db-secret

