apiVersion: apps/v1
kind: ReplicaSet
metadata:
  creationTimestamp: "2020-04-29T08:54:22Z"
  generation: 1
  name: new-replica-set
  namespace: default
  resourceVersion: "1044"
  selfLink: /apis/apps/v1/namespaces/default/replicasets/new-replica-set
  uid: 35c5d142-d964-4b41-9928-1975e3454ff6
spec:
  replicas: 4
  selector:
    matchLabels:
      name: busybox-pod
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: busybox-pod
    spec:
      containers:
        - command:
            - sh
            - -c
            - echo Hello Kubernetes! && sleep 3600
          image: busybox777
          imagePullPolicy: Always
          name: busybox-container
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  fullyLabeledReplicas: 4
  observedGeneration: 1
  replicas: 4