apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
spec:
  containers:
    - name: simple-webapp-color
      image: simple-webapp-color
      ports:
        - containerPort: 8080
      env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: application-config
              key: APP_NAME
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:
              name: application-config
              key: APP_COLOR
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: application-config
              key: APP_ENV
