apiVersion: v1
kind: Pod
metadata:
  name: fluent-ui
  labels:
    name: fluent-ui
spec:
  containers:
  - name: fluent-ui
    image: kodekloud/fluent-ui-running
    ports:
    - containerPort: 80
    - containerPort: 24224