apiVersion: apps/v1
kind: Deployment
metadata:
  name:  bkapp-deployment
  labels:
    app:  bkapp
    type: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      name: bkapp-pod
      labels:
        app: bkapp
        type: front-end
    spec:
      containers:
        - name: nginx
          image: nginx
