apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
    type: front-end
  name: nginx-deployment
spec:
  template:
    metadata:
      labels:
        run: nginx
        type: front-end 
    spec:
      containers:
      - image: nginx
        name: nginx
  selector:
    matchLabels:
      type: front-end
  replicas: 3
