apiVersion: v1
kind: ReplicationController
metadata:
  name: bkapp-rc
  labels:
    app: bkapp
    type: front-end
spec:
  template:
    metadata:
      labels:
        app: bkapp
        type: front-end
      name: bkapp-pod
    spec:
      containers:
      - image: nginx
        name: nginx-container
  replicas: 3



