apiVersion: v1
kind: Service
metadata:
  name:  bkapp-service
spec:
  selector:
    app:  bkweb-app
    type: front-end
  type:  NodePort
  ports:
  - name:  bkwebport
    port:  80
    targetPort:  80
    nodePort: 30009
