apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bharathsnginx
  name: bharathsnginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: bharathsnginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bharathsnginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
