apiVersion: v1
kind: Pod
metadata:
  name: bkapp-pod
  labels:
    app: bkapp
spec:
  containers:
  - name: bkapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo the app is running!! && sleep 3600']
  initContainers:
  - name: init-bkservice
    image: busybox
    command: ['sh', '-c', 'git clone git@github.com:Bharathkumarraju/certified_kubernetes_administrator.git;']
  - name: init-bkdb
    image: busybox
    command: ['sh', '-c', 'until nslookup mydb; do echo waiting for mydb; sleep 2; done;']
