apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    envFrom:                    # whole secret as secretRef
      - secretRef:
          name: db-secret
    env:                       # Add a single secret env 
      - name: DB_Password
        valueFrom:
          secretKeyRef:
            key: DB_password
            name: db-secret
    volumes:                          # Add whole secret object as a volume
      - name:  db-secret-volume
        secret:
          secretName: db-secret