apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: static-busy-box
  name: static-busy-box
spec:
  containers:
    - command:
        - sleep
        - "1000"
      image: busybox
      name: static-busy-box
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}