apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-pod
  name: secret-pod
  namespace: secret
spec:
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  volumes:
    - name: secret1
      secret:
        secretName: secret1

  containers:
  - args:
    - sh
    - -c
    - sleep 5d
    image: busybox:1.31.1
    name: secret-pod
    env:
      - name: APP_USER
        valueFrom:
          secretKeyRef:
            name: secret2
            key: user
      - name: APP_PASS
        valueFrom:
          secretKeyRef:
            name: secret2
            key: pass
    volumeMounts:
    - name: secret1
      mountPath: /tmp/secret1
      readOnly: true

