apiVersion: v1
kind: Pod
metadata:
  labels:
    namne: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - name:  local-persistent-storage
        mountPath:  /var/www/html
  volumes:
    - name: local-persistent-storage
      persistentVolumeClaim:
        claimName: local-pvc
