apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
#  hostPath:
#    path: /tmp/data 
  awsElasticBlockStore:
    volumeID: <volume_id>
    fsType: ext4